version: '3.1'
services:
  testing:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      extension:
        condition: service_started
  extension:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - "GO_BUILDER=golang:1.24"
        - "BASE_IMAGE=ghcr.io/linuxsuren/library/alpine:3.12"
        - GOPROXY=${GOPROXY}
